language: node_js
node_js:
- 6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: required
dist: trusty

env:
- ELASTIC_VERSION="5.6.6"
- ELASTIC_VERSION="5.6.6" DEPLOY="true"

before_script:
- CXX="g++-4.8"
- npm install -g gulp
- wget -O kibana.tar.gz https://github.com/elastic/kibana/archive/v${ELASTIC_VERSION}.tar.gz
- mkdir -p kibana && tar -zxf kibana.tar.gz -C kibana --strip-components=1
- sh -c 'cd kibana && npm install'
- curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTIC_VERSION}.deb && sudo dpkg -i --force-confnew elasticsearch-${ELASTIC_VERSION}.deb && sudo service elasticsearch restart
- curl -O https://raw.githubusercontent.com/rockymadden/transfer-cli/master/src/transfer && chmod +x transfer
- pip install requests[security]
- pip install --user mkdocs

script:
- mkdocs build
- gulp build
- gulp package
- bash test.sh

deploy:
  provider: releases
  file_glob: true
  api_key:
    secure: "CXwnbq7fB3Qun495+IlbHt/b+2zuk3AsO9BFCsyTA6Y8jtrfAWvy+b0cVmTYUSrAQ1P1A1r5y4EjWxNGD59Z8nOosOPzzWxeqkDEyn1s16Q5NP1eJd+pcGSPTkxAJ1Tk/cx+c98U+p8TiIhAPv2TuJL9WIhD4EDyewPOvCS9dVk7g8XHF0pMbH8DTLX6IidegffDiM+yjsxr/5CgfbYrQUKcxiXYw7uIL7+/TeCOMep8yrFYaoYn4ZkBqOMNlEBZPXtKKwk/UR0bG/dul6n7OWehRa1o9WGDhW5DgyoSKOLyQvwaKB7zvztPKlVhk4ngu3pAlCw6lAwDqyk1FUQrzAw7vWjWtnSxo1pVH9Z0vdyYU3qKgL9mr3vB6Fs/n/c/ZNheLrFd4pluKbYSKVYvn1FjqYTNfVDAK4OLEXY58YZ69O6JYArFyUb9aSOSyHNqRCKiFiHAelnH5lLmApcvVD1NhGaVKx5UjB3/GYY1wbzeU4s3gq+Z7BT0BMRD9h8vppkpcFcTzylE68N4Ekt7VxtIUHfQ4SSuEMX3BUhG8pOWVef/LVwaI/rUn5SdB0Op8CtOY6GU6y2MpHOncO8TabbklUDYFGjxTDNigZSi9mIgHboZ1P6CR92QjGJxfBF4CQG+tggTJzAyNVQbqKn3xX7pCI/EbeJZr5qyYJiolCw="
  file: target/mathlion-*.zip
  skip_cleanup: true
  draft: true
  on:
    repo: lvlds/mathlion
    tags: true
    condition: "$DEPLOY = true"
notifications:
  email: false
  slack:
    secure: "cFlLzNkr2Pd+yjMh0yza1Me69ymutLqIAYo6FMpCnlk0zFw2CVlCCz54E/u2hF1ZbVcwb0OBHhmJ6U5h2lznjcBHMZLeAC4uob0SAHJOcqi9vALg3wtanke5GNfJbZrV4PmocYRJBTXWT9ADfLS0okf+AU0xMrH2XPKFU726aA/0A/+qzc4uu/SgZwfJesHejV3qVIsfQHDaWIyuhr7/ywUGwL34YIgGZbVhr6zNlmVVWg4AmzShZYoXpOB6Cl8JkCTVMyHW9AYN+tRY4zdxvu6rZR2slZJcyfaNfuLO1UkmO09RqoCSoyLt4lGdHXm18GI+u4FIM+z2foFuSlGeVG7k+vxSZYMJTnr1GaONA6hCERb8FV4N983inPg/LGcdMm+z3BWUO/WeNXRkEyvxU5m2Hx/JyGibOOMB+buYXzGbCo5+xnTO+JCXCKYGKH1oOy2s+AdgcvzNhYmMoNf7HwOUDBPaqub6jE1x7ThRxXfdoOnrZp8NfOectqVyy5pVBvlu2pcKaWpm/eQSGDKSuqyNfny8gQhyoyuutNZV//JefYWefJKKuwQ5jiVT3AQn+tUlp2tKjl60SV0uaX+GzKWlwGTcEGGzfihDrG5Z3IOLN2TwYUJRFJ/vHshIiUajfNkduPLkDeNgNmayqSxqaefdnzpHVgaNwqAm7v0D4nw="
